name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.10.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build, tag, and push image to Amazon ECR
        run: |
          IMAGE_TAG=$(date +'%Y%m%d%H%M%S')
          docker-compose build
          docker tag app:latest 866934333672.dkr.ecr.us-west-2.amazonaws.com/dharan-snehith-app:$IMAGE_TAG
          docker push 866934333672.dkr.ecr.us-west-2.amazonaws.com/dharan-snehith-app:$IMAGE_TAG
          echo "IMAGE_URI=866934333672.dkr.ecr.us-west-2.amazonaws.com/dharan-snehith-app:$IMAGE_TAG" >> $GITHUB_ENV

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Set up EKS cluster context
        run: |
          aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name dharan-cluster

      - name: Update Kubernetes deployment file
        run: |
          sed -i "s|image:.*|image: ${{ env.IMAGE_URI }}|" ./k8s/app-deployment.yaml

      - name: Apply Kubernetes configurations
        run: |
          kubectl apply -f ./k8s/app-deployment.yaml
          kubectl apply -f ./k8s/mysql-deployment.yaml

      - name: Verify deployment
        run: kubectl rollout status deployment/flask-app
